version: "3"


services:
  webserver:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - app

  app:
     build: ./php/
     container_name: app 
     restart: unless-stopped
     tty: true
     volumes:
      - ./:/var/www 
     networks:
      - app-network

networks:
  app-network:
    driver: bridge