version: "3"


services:
  webserver:
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./public/index.php:/var/www/public/index.php
      - ./public/assets:/var/www/public/assets
      - ./public/screenshots:/var/www/public/screenshots
      - ./api:/var/www/api
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - app

  app:
     build: .
     container_name: app 
     restart: unless-stopped
     tty: true
     volumes:
      - ./src:/var/www/src
      - ./public/index.php:/var/www/public/index.php
      - ./api:/var/www/api
      - ./.env:/var/www/.env

     networks:
      - app-network

networks:
  app-network:
    driver: bridge
