version: "3"


services:
  app:
    build:
      context: ./php
      dockerfile: Dockerfile 
    container_name: app 
    restart: unless-stopped
    tty: true
    volumes:
    - ./public/index.php:/var/www/public/index.php
    - ./api:/var/www/api
    - ./src:/var/www/src
    - ./.env:/var/www/.env

    networks:
    - app-network

  webserver:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: final
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/public
      - ./api:/var/www/api
    networks:
      - app-network
    depends_on:
      - app


networks:
  app-network:
    driver: bridge
