#
# Frontend (Compiling SASS and JS)
#

FROM node:14.9 as frontend

WORKDIR /app

COPY frontend/package*.json ./
COPY frontend/webpack.*.js ./
COPY frontend/gulpfile.js ./

RUN npm install

COPY frontend/js ./js
COPY frontend/scss ./scss

RUN npm run production




FROM nginx:latest

WORKDIR var/www

COPY --from=frontend /app/node_modules/ ./node_modules/
COPY --from=frontend /app/static/js/ ./public/js/
COPY --from=frontend /app/static/css/ ./public/css/

